#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 02 19:16:48 EDT 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=photon_v1.3b.zip
